services:

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    networks:
      - network
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    env_file:
      - ./.env
    environment:
      MARIADB_DATABASE: organic
      MARIADB_USER: nmatondo
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    healthcheck:
      test: ["CMD-SHELL", "mariadb -u root -p$$(cat /run/secrets/db_root_password) -e 'SELECT 1' >/dev/null 2>&1"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "9000:9000"
    networks:
      - network
    restart: always
    env_file:
      - ./.env
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: organic
      WORDPRESS_DB_USER: nmatondo
      DOMAIN_NAME: nmatondo.42.fr
    secrets:
      - db_password
      - credentials
    volumes:
      - wordpress_data:/var/www/html

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - network
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - ./.env
    labels:
      - "desktop.docker.io/wsl-distro=Ubuntu"
      - "com.docker.compose.project=inception"
      - "desktop.docker.io/port.443/protocol=https"
      - "desktop.docker.io/port.443/host=nmatondo.42.fr"

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  credentials:
    file: ../secrets/credentials.txt

networks:
  network:

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
    